name: Trigger auto deployment for robot-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/robot-app-AutoDeployTrigger-a0862edb-a022-4a9c-8209-e5d801af9cfe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ROBOTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ROBOTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ROBOTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.ROBOTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ROBOTAPP_REGISTRY_PASSWORD }}
          containerAppName: robot-app
          resourceGroup: Robot_App_group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


